### ISSUE TITLE
Add new css variables - Reorganize variables

### ISSUE THREAD

**Issue by ail3ngrimaldi** [virto-network/website#15]
Old commit: 

6984d68bdb7914dafe924d1ec505fd7b8371d57a Delete old variables
eba1df684b68568eb33775befe3001cc16d4abcf Add new variables

Refactors:
47fcf610f2ccfb204d43cc4edad5357d790f7359 Color
ff701ad059473f6133f77b45f115252d4b0de0bd Padding and margin
cf055f95956573e1c0880846e861b25c2220ff6e Font size
8b83011af83f0b5ff45eacce6e11b2fd541ac589 Font weight

```css 
@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;300;400;500;600;700;800;900&display=swap');

:root {
  --clr-white: hsl(150, 9%, 96%);
  --clr-black: #000;
  --clr-green-darker: #56c95f;
  --clr-green-lighter: #b6f1b3;
  --clr-olive-darker: hsl(163, 49%, 14%);
  --clr-olive-lighter: hsl(160, 8%, 79%);
  --clr-lavender-darker: hsl(269, 54%, 56%);
  --clr-lavender-lighter: hsl(271, 48%, 87%);
  --clr-blue-darker: hsl(200, 96%, 55%);
  --clr-blue-lighter: hsl(193, 77%, 81%);
  --nav-height: calc(4rem + 2vh);
  --font-primary: 'Outfit', sans-serif;
  --font-secondary: 'Plus Jakarta Sans', sans-serif; 
  --step--2: clamp(0.50rem, calc(0.43rem + 0.35vw), 0.72rem);
  --step--1: clamp(0.75rem, calc(0.65rem + 0.52vw), 1.08rem);
  --step-0: clamp(1.13rem, calc(0.97rem + 0.78vw), 1.63rem);
  --step-1: clamp(1.69rem, calc(1.45rem + 1.17vw), 2.44rem);
  --step-2: clamp(2.53rem, calc(2.18rem + 1.75vw), 3.66rem);
  --margin: 1rem;
  --padding: 1em;
}```

```css 
@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;300;400;500;600;700;800;900&display=swap');

:root {
    /*colores diseño home*/
    --clr-background-pablo: #A8E6A5;
    --clr-letter-pablo: #8f5dd0;
    --clr-lila-pablo: #BD9FE3;
    --clr-footer: #DECFF1;
    --clr-verde-pablo: #1C4334;
    --clr-bg: #10352B;
    --clr-verde-2: #51CB5A;
    --clr-white: #F3F5F4;
    --clr-whitest: #FFFFFF;
    --clr-blackest: #000;
    --clr-grey: #90A19C;
    /*colores brandbook*/
    --clr-green-darker: #56c95f;
    --clr-green-lighter: #b6f1b3;
    --clr-olive-darker: #12352b;
    --clr-olive-lighter: hsl(160, 8%, 79%);
    --clr-lavender-darker: hsl(269, 54%, 56%);
    --clr-lavender-lighter: hsl(271, 48%, 87%);
    --clr-blue-darker: hsl(200, 96%, 55%);
    --clr-blue-lighter: hsl(193, 77%, 81%);
    --nav-height: calc(4rem + 2vh);
    --font-primary: 'Outfit', sans-serif;
    --font-secondary: 'Plus Jakarta Sans', sans-serif;
    --step--2: clamp(0.50rem, calc(0.43rem + 0.35vw), 0.72rem);
    --step--1: clamp(0.75rem, calc(0.65rem + 0.52vw), 1.08rem);
    --step-0: clamp(1.13rem, calc(0.97rem + 0.78vw), 1.63rem);
    --step-1: clamp(1.69rem, calc(1.45rem + 1.17vw), 2.44rem);
    --step-2: clamp(2rem, calc(2.18rem + 1.75vw), 3.66rem);
    --margin: 1rem;
    --padding: 1em;
    --max-width: 1100px;
}

```
Problems to solve

- [x] Non descriptable variable names
- [x] Variables with very similar values
- [ ] Unused variables
- [ ] Some variables have non responsive values
